const IDS = {
  matematicas_general: "Matemáticas General",
  quimica: "Química",
  introduccion_medicina_veterinaria: "Introducción a la Medicina Veterinaria",
  taller_comunicacion_oral_escrita: "Taller de Comunicación Oral y Escrita",
  biologia_celular: "Biología Celular",

  bioestadistica: "Bioestadística",
  bioquimica: "Bioquímica",
  ingles_1: "Inglés I",
  histoembriologia: "Histoembriología",
  anatomia_del_camino: "Anatomía del Camino",

  ingles_2: "Inglés II",
  medio_ambiente_gestion_ambiental: "Medio Ambiente y Gestión Ambiental",
  zoologia: "Zoología",
  practica_basica: "Práctica Básica",
  anatomia_comparada: "Anatomía Comparada",

  fisiologia_animal: "Fisiología Animal",
  microbiologia_general_veterinaria: "Microbiología General y Veterinaria",
  genetica: "Genética",
  administracion_emprendimiento_veterinario: "Administración y Emprendimiento Veterinario",
  enfermedades_parasitarias: "Enfermedades Parasitarias",

  inmunologia: "Inmunología",
  reproduccion_inseminacion_artificial: "Reproducción e Inseminación Artificial",
  tecnologia_alimentos: "Tecnología de los Alimentos",
  nutricion_alimentacion_animal: "Nutrición y Alimentación Animal",
  etologia_bienestar_animal: "Etología y Bienestar Animal",
  fisiopatologia: "Fisiopatología",

  patologia_sistemas: "Patología de Sistemas",
  farmacologia_toxicologia: "Farmacología y Toxicología",
  produccion_avicola: "Producción Avícola",
  enfermedades_infecciosas: "Enfermedades Infecciosas",
  control_calidad_alimentos: "Control de Calidad de los Alimentos",
  obstetricia_ginecologia: "Obstetricia y Ginecología",

  practica_intermedia: "Práctica Intermedia",
  epidemiologia_veterinaria: "Epidemiología Veterinaria",
  produccion_porcina: "Producción Porcina",
  produccion_ovinos_caprinos: "Producción Ovinos y Caprinos",
  semiologia: "Semiología",
  laboratorio_clinico: "Laboratorio Clínico",

  medicina_animales_exoticos: "Medicina de Animales Exóticos",
  medicina_animales_mayores: "Medicina de Animales Mayores",
  medicina_felinos: "Medicina de Felinos",
  medicina_caninos: "Medicina de Caninos",
  cirugia_general: "Cirugía General",

  metodologia_investigacion: "Metodología de la Investigación",
  diagnostico_imagenes: "Diagnóstico por Imágenes",
  practica_final: "Práctica Final",
  formulacion_evaluacion_proyectos_agropecuarios: "Formulación y Evaluación de Proyectos Agropecuarios",
  produccion_acuicola: "Producción Acuícola",
  patologia_quirurgica: "Patología Quirúrgica",
  produccion_bovinos_carne_leche: "Producción de Bovinos de Carne y Leche",

  farmacologia_aplicada: "Farmacología Aplicada",
  salud_publica: "Salud Pública",
  trabajo_titulacion: "Trabajo de Titulación",
  clinica_animales_menores: "Clínica de Animales Menores",
  clinica_animales_mayores: "Clínica de Animales Mayores"
};
