// script.js actualizado con orden por semestre

const ramos = { "matematicas general": { requisitos: [], desbloquea: ["bioestadística"], semestre: 1 }, "quimica": { requisitos: [], desbloquea: ["bioquímica"], semestre: 1 }, "introducción a la medicina veterinaria": { requisitos: [], desbloquea: ["practica basica"], semestre: 1 }, "taller de com. oral y escrita": { requisitos: [], desbloquea: [], semestre: 1 }, "biologia celular": { requisitos: [], desbloquea: ["medio ambiente y gestión ambiental", "microbiología general y veterinaria"], semestre: 1 },

"bioestadística": { requisitos: ["matematicas general"], desbloquea: ["genetica"], semestre: 2 }, "bioquímica": { requisitos: ["quimica"], desbloquea: ["fisiología animal", "nutrición y alimentación animal"], semestre: 2 }, "ingles 1": { requisitos: [], desbloquea: ["ingles 2"], semestre: 2 }, "histoembriología": { requisitos: [], desbloquea: ["zoología"], semestre: 2 }, "anatomia del camino": { requisitos: [], desbloquea: ["practica basica", "anatomia comparada"], semestre: 2 },

"ingles 2": { requisitos: ["ingles 1"], desbloquea: [], semestre: 3 }, "medio ambiente y gestión ambiental": { requisitos: ["biologia celular"], desbloquea: ["producción porcina"], semestre: 3 }, "zoología": { requisitos: ["histoembriología"], desbloquea: ["enfermedades parasitarias", "etología y bienestar animal", "fisiopatología"], semestre: 3 }, "practica basica": { requisitos: ["introducción a la medicina veterinaria", "anatomia del camino"], desbloquea: [], semestre: 3 }, "anatomia comparada": { requisitos: ["anatomia del camino"], desbloquea: ["fisiología animal", "semiología"], semestre: 3 },

"fisiología animal": { requisitos: ["bioquímica", "anatomia comparada"], desbloquea: ["reproducción e inseminación artificial", "farmacología y toxicología"], semestre: 4 }, "microbiología general y veterinaria": { requisitos: ["biologia celular"], desbloquea: ["inmunología", "tecnologia de los alimentos"], semestre: 4 }, "genetica": { requisitos: ["bioestadística"], desbloquea: ["producción ovinos y caprinos"], semestre: 4 }, "administración y emprendimiento veterinario": { requisitos: [], desbloquea: ["formulación y evaluación de proyectos agropecuarios"], semestre: 4 }, "enfermedades parasitarias": { requisitos: ["zoología"], desbloquea: ["control de calidad de los alimentos"], semestre: 4 },

"inmunología": { requisitos: ["microbiología general y veterinaria"], desbloquea: ["enfermedades infecciosas"], semestre: 5 }, "reproducción e inseminación artificial": { requisitos: ["fisiología animal"], desbloquea: ["obstetricia y ginecología", "producción porcina"], semestre: 5 }, "tecnologia de los alimentos": { requisitos: ["microbiología general y veterinaria"], desbloquea: ["control de calidad de los alimentos"], semestre: 5 }, "nutrición y alimentación animal": { requisitos: ["bioquímica"], desbloquea: ["producción avícola", "producción acuícola"], semestre: 5 }, "etología y bienestar animal": { requisitos: ["zoología"], desbloquea: ["producción avícola"], semestre: 5 }, "fisiopatología": { requisitos: ["zoología"], desbloquea: ["patología de sistemas", "semiología"], semestre: 5 },

"patología de sistemas": { requisitos: ["fisiopatología"], desbloquea: ["laboratorio clinico", "diagnostico por imagenes"], semestre: 6 }, "farmacología y toxicología": { requisitos: ["fisiología animal"], desbloquea: ["practica intermedia", "semiología"], semestre: 6 }, "producción avícola": { requisitos: ["nutrición y alimentación animal", "etología y bienestar animal"], desbloquea: [], semestre: 6 }, "enfermedades infecciosas": { requisitos: ["inmunología"], desbloquea: ["practica intermedia", "epidemiología veterinaria"], semestre: 6 }, "control de calidad de los alimentos": { requisitos: ["tecnologia de los alimentos", "enfermedades parasitarias"], desbloquea: ["salud publica"], semestre: 6 }, "obstetricia y ginecología": { requisitos: ["reproducción e inseminación artificial"], desbloquea: ["producción de bovinos de carne y leche"], semestre: 6 },

"practica intermedia": { requisitos: ["farmacología y toxicología", "enfermedades infecciosas"], desbloquea: ["practica final"], semestre: 7 }, "epidemiología veterinaria": { requisitos: ["enfermedades infecciosas"], desbloquea: ["metodología de la investigación", "salud publica"], semestre: 7 }, "producción porcina": { requisitos: ["medio ambiente y gestión ambiental", "reproducción e inseminación artificial"], desbloquea: [], semestre: 7 }, "producción ovinos y caprinos": { requisitos: ["genetica"], desbloquea: [], semestre: 7 }, "semiología": { requisitos: ["anatomia comparada", "farmacología y toxicología", "fisiopatología"], desbloquea: ["medicina de animales exoticos", "medicina de animales mayores", "medicina de felinos", "medicina de caninos", "cirugia general"], semestre: 7 }, "laboratorio clinico": { requisitos: ["patología de sistemas"], desbloquea: ["medicina de animales exoticos", "medicina de animales mayores", "medicina de felinos", "medicina de caninos"], semestre: 7 },

"medicina de animales exoticos": { requisitos: ["semiología", "laboratorio clinico"], desbloquea: [], semestre: 8 }, "medicina de animales mayores": { requisitos: ["semiología", "laboratorio clinico"], desbloquea: ["clinica de animales mayores", "farmacología aplicada"], semestre: 8 }, "medicina de felinos": { requisitos: ["semiología", "laboratorio clinico"], desbloquea: [], semestre: 8 }, "medicina de caninos": { requisitos: ["semiología", "laboratorio clinico"], desbloquea: ["clinica de animales menores", "farmacología aplicada"], semestre: 8 }, "cirugia general": { requisitos: ["semiología"], desbloquea: ["patologia quirurgica"], semestre: 8 },

"metodología de la investigación": { requisitos: ["epidemiología veterinaria"], desbloquea: ["trabajo de titulación"], semestre: 9 }, "diagnostico por imagenes": { requisitos: ["patología de sistemas"], desbloquea: ["clinica de animales mayores", "clinica de animales menores"], semestre: 9 }, "practica final": { requisitos: ["practica intermedia"], desbloquea: [], semestre: 9 }, "formulación y evaluación de proyectos agropecuarios": { requisitos: ["administración y emprendimiento veterinario"], desbloquea: [], semestre: 9 }, "producción acuícola": { requisitos: ["nutrición y alimentación animal"], desbloquea: [], semestre: 9 }, "patologia quirurgica": { requisitos: ["cirugia general"], desbloquea: [], semestre: 9 }, "producción de bovinos de carne y leche": { requisitos: ["obstetricia y ginecología"], desbloquea: [], semestre: 9 },

"farmacología aplicada": { requisitos: ["medicina de animales mayores", "medicina de caninos"], desbloquea: [], semestre: 10 }, "salud publica": { requisitos: ["control de calidad de los alimentos", "epidemiología veterinaria"], desbloquea: [], semestre: 10 }, "trabajo de titulación": { requisitos: ["metodología de la investigación"], desbloquea: [], semestre: 10 }, "clinica de animales menores": { requisitos: ["medicina de caninos", "diagnostico por imagenes"], desbloquea: [], semestre: 10 }, "clinica de animales mayores": { requisitos: ["medicina de animales mayores", "diagnostico por imagenes"], desbloquea: [], semestre: 10 } };

const malla = documento.obtener Elemento por Id("Malla");

para (const [nombre, datos] of Objeto.entradas(ramos)) { const Div. = documento.crear elemento elemento("Div"); Div..claseLista.Añadir("Ramo"); Div..interiorTexto = nombre; Si (datos.requisitos.length > 0) div.classList.add("bloqueado"); div.addEventListener("click", () => aprobarRamo(nombre, div));

const contenedor = documento.querySelector([datos-Semestre='${datos.semestre}']); Si (contenedor) contenedor.apender niño niño(Div.); }

  función   aprobarRamo(nombre, Div.) { Si (Div..claseLista.contiene("bloqueado")) volver; Div..claseLista.alternar("aprobado"); actualizarEstado(); }

función actualizarEstado() { const aprobados = nuevo Set( Array.de(documento.consultaSelectorAll(".ramo.aprobado")).mapa(e => e.interiorTexto) );

para (const [nombre, datos] of Objeto.entradas(ramos)) { const el = Array.de(documento.consultaSelectorAll("Ramo")).encontrar(e => e.interiorTexto === nombre); Si (datos.requisitos.every(req => aprobados.has(req))) { el.classList.remove("bloqueado"); } else { if (!aprobados.has(nombre)) el.classList.add("bloqueado"); } } }

